server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.100.128:8848
    gateway:
      routes:
        - id: category
          uri: lb://sky-take-out-category
          predicates:
            - Path=/user/category/**,/admin/category/**
        - id: dish
          uri: lb://sky-take-out-dish
          predicates:
            - Path=/user/dish/**,/admin/dish/**
        - id: setmeal
          uri: lb://sky-take-out-setmeal
          predicates:
            - Path=/user/setmeal/**,/admin/setmeal/**
        - id: order
          uri: lb://sky-take-out-order
          predicates:
            - Path=/user/order/**,/admin/order/**
        - id: order-ws
          uri: lb:ws://sky-take-out-order
          predicates:
            - Path=/ws/**
        - id: shop
          uri: lb://sky-take-out-shop
          predicates:
            - Path=/user/shop/**,/admin/shop/**
        - id: employee
          uri: lb://sky-take-out-employee
          predicates:
            - Path=/admin/employee/**
        - id: workspace
          uri: lb://sky-take-out-workspace
          predicates:
            - Path=/admin/workspace/**
        - id: address
          uri: lb://sky-take-out-address
          predicates:
            - Path=/user/address/**,/user/addressBook/**
        - id: report
          uri: lb://sky-take-out-report
          predicates:
            - Path=/admin/report/**
        - id: shoppingcart
          uri: lb://sky-take-out-shoppingcart
          predicates:
            - Path=/user/shoppingCart/**,/user/shoppingcart/**
        - id: user
          uri: lb://sky-take-out-user
          predicates:
            - Path=/user/user/**
sky:
  jwt:
    # 璁剧疆jwt绛惧悕鍔犲瘑鏃朵娇鐢ㄧ殑绉橀挜
    admin-secret-key: itcast
    # 璁剧疆jwt杩囨湡鏃堕棿
    admin-ttl: 7200000
    # 璁剧疆鍓嶇浼犻€掕繃鏉ョ殑浠ょ墝鍚嶇О
    admin-token-name: token
    # 璁剧疆jwt绛惧悕鍔犲瘑鏃朵娇鐢ㄧ殑绉橀挜
    user-secret-key: itcast
    # 璁剧疆jwt杩囨湡鏃堕棿
    user-ttl: 7200000
    # 璁剧疆鍓嶇浼犻€掕繃鏉ョ殑浠ょ墝鍚嶇О
    user-token-name: authentication
    excludePaths: # 鏃犻渶鐧诲綍鏍￠獙鐨勮矾寰?
      - /user/user/login
      - /user/shop/status
      - /admin/employee/login
feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持

