sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out_category
    username: root
    password: yangshun011110
  alioss:
    bucket-name: wudixiaoxuesheng-ai
    access-key-id: LTAI5t9nJ2a4XWxL37zeLwqL
    access-key-secret: oMe02U0cGXkeLAr70nVsYyjl1KQzvU
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    database: 2
  wechat:
    # 浠ュ悗鐢ㄥ埌鐨勬椂鍊檃ppid secret mechid No Path绛夋崲鎴愯嚜宸辩殑鍗冲彲
    appid: wx74d1255221847526
    secret: 0fc345a8c234115e608e836185e65adb
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php

