server:
  port: 8088

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    database: ${sky.redis.database}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: sky-take-out-workspace
  cloud:
    nacos:
      server-addr: 192.168.100.128:8848
    sentinel:
      transport:
        dashboard: localhost:9090
      http-method-specify: true # 开启请求方式前缀
mybatis-plus:
  #mapper-plus閰嶇疆鏂囦欢
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #寮€鍚┘宄板懡鍚?
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto # 鍏ㄥ眬id绫诲瀷涓鸿嚜澧為暱

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    mchid : ${sky.wechat.mchid}
    mchSerialNo: ${sky.wechat.mchSerialNo}
    privateKeyFilePath: ${sky.wechat.privateKeyFilePath}
    apiV3Key: ${sky.wechat.apiV3Key}
    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath}
    notifyUrl: ${sky.wechat.notifyUrl}
    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}
  shop:
    address: 鍖椾含甯傛捣娣€鍖轰笂鍦板崄琛?0鍙?
  baidu:
    ak: 9eptLzUStYTTWzqsPwGF9XiCfuZDLUZp
 
feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持


